version: '3.1'

services:
  app:
    build: .
    image: api/docker-node
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/app/
    ports:
      - "${APP_PORT}:${APP_PORT}"
   
    depends_on:
      - mongo
    links:
       - mongo

  mongo:
     image: mongo:5.0.2
     container_name: mongo-demon-api
     restart: always
     ports:
       - "${DB_PORT_APP}:${DB_PORT}"
     env_file:
       - .env

     volumes:
       - .:/app/data

volumes:
   db:
